### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by ruckc** [indeedeng/util#9]
Being that you have numerous libraries that depend on this (lsmtree in my case) it would be beneficial to provide a windows library.

**Comment by jpitz** [comment]
Did you mean to open this in the lsmtree project?

**Comment by jpitz** [comment]
Unfortunately no one in our office uses Windows. Making progress on this might take a little bit of time. @ruckc, since it sounds like you actively develop on windows would you mind putting up some pull requests to attack this issue? To help break things down, we can probably do some smaller issues that attack modules independently.

Looking specifically at the lsmtree project pom file, it looks like these are the dependencies within the util project:

* util-compress
* util-core
* util-mmap
* util-io
* util-serialization
* util-varexport

The ```mmap``` library is probably going to be the biggest one to attack as it requires compiling the native binary on the given platform (from what I can remember).

The ```compress``` library requires snappy to be installed on the machine. From what I can tell, Snappy is available on Windows so this should be a non-issue but wouldn't hurt to check.

The ```io``` library deals with a lot of file system manipulation. Given that, I'm sure there are several system calls that won't work on windows either.

**Comment by mmorrisontx** [comment]
Closing all issues, as this repository is now archived.
